language: python

python: 3.6

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE test_djforum;" -U postgres
  - psql -c "CREATE USER djadmin WITH CREATEUSER PASSWORD '@sanghvi@';" -U postgres
  - psql -c "ALTER USER root CREATEDB;" -U postgres
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - python3 manage.py test

notifications:
  email:
    recipients:
      - vikrantgajria@gmail.com
    on_success: always
    on_failure: always
